name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Lint contracts
        run: cd packages/contracts && pnpm lint
        
      - name: Lint frontend
        run: cd packages/frontend && pnpm lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build contracts
        run: cd packages/contracts && pnpm compile
        
      - name: Build frontend
        run: cd packages/frontend && pnpm build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Run contract tests
        run: cd packages/contracts && pnpm test
        
      - name: Run frontend tests
        run: cd packages/frontend && pnpm test --passWithNoTests

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Deploy to Xsolla ZK Sepolia
        run: |
          cd packages/contracts
          pnpm deploy:xsolla
        env:
          XSOLLA_ZK_SEPOLIA_RPC: ${{ secrets.XSOLLA_ZK_SEPOLIA_RPC }}
          XSOLLA_ZK_CHAIN_ID: ${{ secrets.XSOLLA_ZK_CHAIN_ID }}
          ETH_SEPOLIA_RPC: ${{ secrets.ETH_SEPOLIA_RPC }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
